MACOSX_SDK_VERSION:  # [osx and x86_64]
  - 10.15            # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.15"                # [osx and x86_64]
channel_targets:
  - tiledb main
channel_sources:
  - conda-forge
channel_priority:
  - strict
tiledb:
- '2.15.*'
- '2.16.*'
numpy:
  - 1.21
  - 1.21
  - 1.23
python:
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
python_impl:
  - cpython
  - cpython
  - cpython
