MACOSX_SDK_VERSION:  # [osx and x86_64]
  - 10.15            # [osx and x86_64]
c_stdlib_version:    # [osx and x86_64]
  - "10.15"          # [osx and x86_64]
channel_targets:
  - tiledb main
channel_sources:
  - conda-forge
channel_priority:
  - strict
numpy:
  - 2.0.0
  - 2.0.0
  - 2.0.0
python:
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython
python_impl:
  - cpython
  - cpython
  - cpython
is_python_min:
  - 3.9
  - 3.10
  - 3.11
zipped_keys:
  - [python, python_impl, numpy]
