MACOSX_SDK_VERSION:  # [osx and x86_64]
  - 10.15            # [osx and x86_64]
c_stdlib_version:    # [osx and x86_64]
  - "10.15"          # [osx and x86_64]
channel_targets:
  - tiledb main
channel_sources:
  - conda-forge
channel_priority:
  - strict
numpy:
  - 1.22
  - 1.22
  - 1.23
python:
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
python_impl:
  - cpython
  - cpython
  - cpython
