{% set name = "tiledb-vector-search" %}
{% set version = "0.0.1" %}
#{% set sha256 = "ac01357ed1f793fe96f728e4abb4965c7303918510cec38fda1ea5ef5ad47643" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  #path: "/home/conda/feature-vector-prototype"
  #url: https://github.com/TileDB-Inc/feature-vector-prototype/archive/{{ version }}.tar.gz
  #url: https://github.com/TileDB-Inc/feature-vector-prototype/archive/main.tar.gz
  #url: https://github.com/TileDB-Inc/feature-vector-prototype/archive/gitattributes.tar.gz
  git_url: https://github.com/TileDB-Inc/TileDB-Vector-Search.git
  git_rev: main
  #git_depth: 1 # (Defaults to -1/not shallow)
#  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win32]
  skip: true  # [win and py2k]
requirements:
  build:
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake
    - make  # [not win]
    - libopenblas                            # [build_platform != target_platform]
    - openblas                            # [build_platform != target_platform]
  host:
    - pip
    - wheel
    - setuptools
    - setuptools_scm
    - python
    - numpy
    - pybind11
    - tiledb 2.15.*
    - tiledb-py
    - scikit-build
    - libopenblas
    - openblas
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - tiledb 2.15.*
    - tiledb-py
    - scikit-build
    - libopenblas
    - openblas

about:
  home: http://tiledb.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TileDB Vector Search
  description: |
    TileDB-Vector-Search is the python interface to the TileDB array storage manager.
    TileDB  is an efficient multi-dimensional array management system which introduces
    a novel on-disk format that can store dense and sparse array data with
    support for fast reads and updates and reads. It features excellent compression, and an efficient
    parallel I/O system with high scalability.
  doc_url: https://github.io/TileDB-Inc/TileDB-Vector-Search
  dev_url: https://github.com/TileDB-Inc/TileDB-Vector-Search

extra:
  recipe-maintainers:
    - shelnutt2
    - ihnorton
