{% set name = "tiledb-vector-search" %}
{% set version = "0.0.6" %}
{% set sha256 = "22c244d7206a0f862d7c05d5c36f896fb31c617c0b3997277bf6ef6afcaf5685" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # NOTE: using git versions so that setuptools_scm works, until we build from PyPI
  #url: https://github.com/TileDB-Inc/feature-vector-prototype/archive/{{ version }}.tar.gz
  #sha256: {{ sha256 }}
  git_url: https://github.com/TileDB-Inc/TileDB-Vector-Search.git
  git_rev: {{ version }}
  git_depth: 1 # (Defaults to -1/not shallow)

build:
  number: 0
  skip: true  # [win32]
  skip: true  # [win and py2k]
  skip: true  # [win]
requirements:
  build:
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake
    - make  # [not win]
    - libopenblas                            # [build_platform != target_platform]
    - openblas                            # [build_platform != target_platform]
  host:
    - pip
    - wheel
    - setuptools
    - setuptools_scm
    - python
    - numpy
    - pybind11
    - tiledb 2.16.*
    - tiledb-py
    - scikit-build
    - libopenblas
    - openblas
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - tiledb 2.16.*
    - tiledb-py
    - scikit-build
    - libopenblas
    - openblas

about:
  home: http://tiledb.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TileDB Vector Search
  description: |
    TileDB-Vector-Search is the python interface to the TileDB array storage manager.
    TileDB  is an efficient multi-dimensional array management system which introduces
    a novel on-disk format that can store dense and sparse array data with
    support for fast reads and updates and reads. It features excellent compression, and an efficient
    parallel I/O system with high scalability.
  doc_url: https://github.io/TileDB-Inc/TileDB-Vector-Search
  dev_url: https://github.com/TileDB-Inc/TileDB-Vector-Search

extra:
  recipe-maintainers:
    - shelnutt2
    - ihnorton
