{% set name = "tiledb-vector-search" %}
{% set version = "0.3.0" %}
{% set sha256 = "76633917d23c63dc4f056f0d27ad51e996a5dc56725fcfa026870829a49e59af" %}
# Pro-tip:
# * Visit https://pypi.org/project/tiledb-vector-search/i.j.k/#files in your browser
# * Download
# * shasum -a 256 it

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tiledb_vector_search-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: TileDB_DIR=${PREFIX} {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  skip: true # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake
    - make  # [not win]
    - libopenblas                            # [build_platform != target_platform]
    - openblas                            # [build_platform != target_platform]
  host:
    - pip
    - wheel
    - scikit-build-core
    - setuptools_scm
    - python
    - numpy
    - pybind11
    - tiledb >=2.22,<2.23
    - tiledb-py
    - libopenblas
    - openblas
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scikit-learn
    - tiledb >=2.22,<2.23
    - tiledb-py
    - libopenblas
    - openblas

test:
  requires:
    - pip
  commands:
    - pip install --prefer-binary tiledb-cloud
    - pip check
    - python -c "import tiledb.vector_search"

about:
  home: https://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TileDB Vector Search
  description: |
    TileDB Vector Search is an open source, lightweight, embeddable, and cloud-native
    vector similarity search database implemented in high-performance C++ with an easy
    Python API.
  doc_url: https://tiledb-inc.github.io/TileDB-Vector-Search
  dev_url: https://github.com/TileDB-Inc/TileDB-Vector-Search

extra:
  recipe-maintainers:
    - shelnutt2
    - ihnorton
