{% set name = "tiledb-vector-search" %}
{% set version = "0.0.20" %}
{% set sha256 = "" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # NOTE: using git versions so that setuptools_scm works, until we build from PyPI
  #url: https://github.com/TileDB-Inc/feature-vector-prototype/archive/{{ version }}.tar.gz
  #sha256: {{ sha256 }}
  git_url: https://github.com/TileDB-Inc/TileDB-Vector-Search.git
  git_rev: {{ version }}
  #git_depth: 1 # (Defaults to -1/not shallow)

build:
  number: 0
requirements:
  build:
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake
    - make  # [not win]
    - libopenblas                            # [build_platform != target_platform]
    - openblas                            # [build_platform != target_platform]
  host:
    - pip
    - wheel
    - setuptools
    - setuptools_scm
    - python
    - numpy
    - pybind11
    - tiledb >=2.19,<2.20
    - tiledb-py
    - scikit-build
    - libopenblas
    - openblas
    - lz4 1.9.4 # [py==39]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scikit-learn
    - tiledb >=2.19,<2.20
    - tiledb-py
    - libopenblas
    - openblas
    - lz4 1.9.4 # [py==39]

about:
  home: https://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TileDB Vector Search
  description: |
    TileDB Vector Search is an open source, lightweight, embeddable, and cloud-native
    vector similarity search database implemented in high-performance C++ with an easy
    Python API.
  doc_url: https://tiledb-inc.github.io/TileDB-Vector-Search
  dev_url: https://github.com/TileDB-Inc/TileDB-Vector-Search

extra:
  recipe-maintainers:
    - shelnutt2
    - ihnorton
