{% set name = "tiledb-vector-search" %}
{% set version = "0.1.0" %}
{% set url = "https://files.pythonhosted.org/packages/39/c0/37f21602a8d1ac1e7c8e91b07059fd97576ada3e8b774d42792caa4b8a6b/tiledb_vector_search-0.1.0.tar.gz" %}
{% set sha256 = "7b2b04915c5393c601443c688bbbb7dd25bba54f1292c22ac3437786538fa6b2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: {{ url }}
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake
    - make  # [not win]
    - libopenblas                            # [build_platform != target_platform]
    - openblas                            # [build_platform != target_platform]
  host:
    - pip
    - wheel
    - scikit-build-core
    - setuptools_scm
    - python
    - numpy
    - pybind11
    - tiledb >=2.20,<2.21
    - tiledb-py
    - libopenblas
    - openblas
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scikit-learn
    - tiledb >=2.20,<2.21
    - tiledb-py
    - libopenblas
    - openblas

about:
  home: https://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TileDB Vector Search
  description: |
    TileDB Vector Search is an open source, lightweight, embeddable, and cloud-native
    vector similarity search database implemented in high-performance C++ with an easy
    Python API.
  doc_url: https://tiledb-inc.github.io/TileDB-Vector-Search
  dev_url: https://github.com/TileDB-Inc/TileDB-Vector-Search

extra:
  recipe-maintainers:
    - shelnutt2
    - ihnorton
