{% set name = "tiledb-vector-search" %}
{% set version = "0.8.0" %}
{% set sha256 = "47bf2884b37fae21fbba430a8cb27e92a0640af80d738577c1fcc6e1794c7479" %}
# Pro-tip:
# * Visit https://pypi.org/project/tiledb-vector-search/i.j.k/#files in your browser
# * Then either:
#   a. Download `tiledb_vector_search-i.j.j.tar.gz` and run `shasum -a 256 it`
#   b. Click `view hashes` for `tiledb_vector_search-i.j.j.tar.gz` and copy the SHA256 hash

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tiledb_vector_search-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: TILEDB_PATH=${PREFIX} {{ PYTHON }} -m pip install --no-build-isolation --no-deps --ignore-installed -v .  # [linux and py==39]
  # Do not include debug info when building binaries that won't be deployed to TileDB Cloud
  script: >-                                                # [not (linux and py==39)]
    TILEDB_PATH=${PREFIX} {{ PYTHON }} -m pip install       # [not (linux and py==39)]
    --no-build-isolation --no-deps --ignore-installed -v .  # [not (linux and py==39)]
    --config-settings=cmake.build-type="Release"            # [not (linux and py==39)]
    --config-settings=install.strip=true                    # [not (linux and py==39)]
  skip: true # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake
    - make  # [not win]
    - libopenblas                            # [build_platform != target_platform]
    - openblas                            # [build_platform != target_platform]
  host:
    - pip
    - wheel
    - scikit-build-core
    - setuptools_scm
    - python
    - numpy
    - pybind11
    - tiledb >=2.25,<2.26
    - tiledb-py
    - libopenblas
    - openblas
  run:
    - python
    - scikit-learn
    - tiledb-py
    - openblas

test:
  requires:
    - pip
  commands:
    - pip install --prefer-binary tiledb-cloud
    - pip check
    - python -c "import tiledb.vector_search"

about:
  home: https://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TileDB Vector Search
  description: |
    TileDB Vector Search is an open source, lightweight, embeddable, and cloud-native
    vector similarity search database implemented in high-performance C++ with an easy
    Python API.
  doc_url: https://tiledb-inc.github.io/TileDB-Vector-Search
  dev_url: https://github.com/TileDB-Inc/TileDB-Vector-Search

extra:
  recipe-maintainers:
    - dudoslav
    - ihnorton
    - jdblischak
    - johnkerl
    - jparismorgan
    - NikolaosPapailiou
    - shelnutt2
    - teo-tsirpanis
