azure:
  build_id: 48
  user_or_org: TileDB-Inc
  project_name: CI
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: false
github:
  branch_name: main
  tooling_branch_name: main
provider:
  win: azure
test: native_and_emulated
conda_build:
  pkg_format: '2'
upload_on_branch: main
